### ISSUE TITLE
Why is counter_test/counter_basys3.v?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-examples#11]
Shouldn't it be `counter_test/counter.v`?

**Comment by mithro** [comment]
FYI - @joannabrozek

**Comment by pgielda** [comment]
I guess its because it, as README states "targets the Basys3 board".
it would still make sense to just rename it for simplicity.

**Comment by mithro** [comment]
@pgielda Most certainly want to add Arty support too...

**Comment by pgielda** [comment]
it is renamed now at least.

**Comment by pgielda** [comment]
I guess its now a duplicate of #6
