### ISSUE TITLE
Source code for picoSoC example firmware

### ISSUE THREAD

**Issue by DrmnSamoLiu** [SymbiFlow/symbiflow-examples#140]
Hi!
I see that the example firmware binary for picoSoC is hardcoded into progmem.v. Are there any chances that you can share the C source code and build parameters so we can experiment with more stuff?
For example I would like to try compiling my own source code and load it from QSPI flash or USB.
Thanks in advance!

**Comment by mithro** [comment]
@acomodi - Any idea?

**Comment by acomodi** [comment]
Hi @DrmnSamoLiu, IIRC, the current firmware that is used in this example was built in here: https://github.com/SymbiFlow/symbiflow-arch-defs/tree/master/tests/9-soc/picosoc/firmware

**Comment by DrmnSamoLiu** [comment]
@mithro @acomodi 
Awesome, appreciate your help!
