### ISSUE TITLE
Openocd: libusb_open() failed with LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by betocool-prog** [SymbiFlow/symbiflow-examples#195]
Hi all,

Apologies if this is the wrong place to ask, but I'm having issues getting my bit file into the ARTY 100 board loaded. Here's what I did so far:

- Installed Symbiflow and all its dependencies as described [here](https://symbiflow-examples.readthedocs.io/en/latest/getting-symbiflow.html): OK
- Ran the script(s) to generate the bit-stream: OK
- Attempted to load the bitstream... fail!

Some additional information.
- I was able, once, to use Vivado to see the hardware. I don't know if that is causing issues, as Vivado is still installed, but it also can't see the hardware now.
- I have a Digilent Analog Discovery 2 board which works with the installed Digilent drivers. That works OK.
- lsusb output:
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 046d:c52e Logitech, Inc. MK260 Wireless Combo Receiver
Bus 001 Device 005: ID 0403:6010 Future Technology Devices International, Ltd FT2232C Dual USB-UART/FIFO IC
Bus 001 Device 002: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
- Error message:
```
(xc7) user@userpc:openocd -f $LONG_PATH/openocd/scripts/board/digilent_arty.cfg -c "init; pld load 0 top.bit; exit"
Open On-Chip Debugger 0.10.0+dev-01514-ga8edbd020-dirty (2020-11-19-16:20)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtagspi_program
Error: libusb_open() failed with LIBUSB_ERROR_ACCESS
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6010, description 'Digilent USB Device', serial '*' at bus location '*'
```
- Xilinx cable drivers and udev rules are installed, but I might have overlooked something there. Should I add my user to the "plugdev" group? But the Analog Discovery works out of the box
- Dmesg output when I plug in the unit:
```
[  +6.619364] usb 1-4: new high-speed USB device number 7 using xhci_hcd
[  +0.153820] usb 1-4: New USB device found, idVendor=0403, idProduct=6010, bcdDevice= 7.00
[  +0.000005] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000003] usb 1-4: Product: Digilent USB Device
[  +0.000003] usb 1-4: Manufacturer: Digilent
[  +0.000002] usb 1-4: SerialNumber: 210319B26BB4
[  +0.006904] ftdi_sio 1-4:1.0: FTDI USB Serial Device converter detected
[  +0.000063] usb 1-4: Detected FT2232H
[  +0.000335] usb 1-4: FTDI USB Serial Device converter now attached to ttyUSB1
[  +0.002207] ftdi_sio 1-4:1.1: FTDI USB Serial Device converter detected
[  +0.000077] usb 1-4: Detected FT2232H
[  +0.000235] usb 1-4: FTDI USB Serial Device converter now attached to ttyUSB2
[  +0.023815] ftdi_sio ttyUSB1: FTDI USB Serial Device converter now disconnected from ttyUSB1
[  +0.000060] ftdi_sio 1-4:1.0: device disconnected
```
It strikes me as odd that is says "Device disconnected" at the end while it's still connected?
This happens when I actually disconnect it:
```
[Oct19 20:44] usb 1-4: USB disconnect, device number 7
[  +0.000281] ftdi_sio ttyUSB2: FTDI USB Serial Device converter now disconnected from ttyUSB2
[  +0.000010] ftdi_sio 1-4:1.1: device disconnected
```

Any help is greatly appreciated! I might be overlooking something very basic...

Cheers,

Alberto

**Comment by mithro** [comment]
You can test this theory by putting `sudo` in front of the `openocd` command (which will make it run as root). That is not a long term solution, but should confirm if it is a typical permission problem or if there is something like SELinux or AppArmor also involved.
