### ISSUE TITLE
Link symbiflow.github.io directly to docs at symbiflow-examples.readthedocs.io/

### ISSUE THREAD

**Issue by alanvgreen** [SymbiFlow/symbiflow-examples#203]
I'm not sure where to file issues for symbiflow.github.io, so filing here.

The "Symbiflow Examples" button on the [Symbiflow wiki Getting Started page](https://symbiflow.github.io/getting-started.html) links to the [README.md for the new user documentation](https://github.com/SymbiFlow/symbiflow-examples) instead of the [actual new user documentation](http://symbiflow-examples.readthedocs.io).

There are links to the documentation from README, but they are not obvious to someone who doesn't know they should be looking for them. I think it would be more helpful for new users if the new user documentation were linked directly rather than via READM.

**Comment by mithro** [comment]
@acomodi / @mgielda

**Comment by mithro** [comment]
@kgugala
