### ISSUE TITLE
Weird issue with /usr/bin/env on symbiflow-examples runners

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-examples#211]
There was a weird failure @ https://github.com/SymbiFlow/symbiflow-examples/runs/4083446723?check_suite_focus=true
```
Run actions/upload-artifact@v2
19:37:55 | bash: line 1: /usr/bin/env: No such file or directory
Error: Process completed with exit code 127.
0s
19:37:55 | Post job cleanup.
19:37:55 | bash: line 1: /usr/bin/env: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by mithro** [comment]
FYI -- @kgugala / @tmichalak

**Comment by mithro** [comment]
Do you think this is the pre-emption issue?

**Comment by pgielda** [comment]
No, this is just some kind of a bug. Happens always on this particular job (centos7 xc7 counter)

**Comment by mithro** [comment]
Seems weird.

**Comment by pgielda** [comment]
I agree, it is super weird. But its on the node "javacript" actions that we've support for recently... so there must be some kind of an edge case where it does not work. Same runners work fine in multiple projects in CHIPS Alliance org.

**Comment by AdamOlech** [comment]
We seem to have fixed the issue. It was most likely related to an erroneous container invocation in the runner code - see https://github.com/antmicro/runner/commit/838478f10244bfd05576c28d38464ac8731e8cc6

**Comment by kgugala** [comment]
This issue doesn't seem to be hitting us anymore. I'm closing the issue, will reopen if it happens again.
