### ISSUE TITLE
examples/xc7/linux_litex_demo serialboot doesn't work with provided Linux images

### ISSUE THREAD

**Issue by tcal-x** [SymbiFlow/symbiflow-examples#42]
See comment https://github.com/SymbiFlow/symbiflow-examples/issues/41#issuecomment-672905413.

I have replicated these results.

**Comment by kgugala** [comment]
the images are fine. `emulator.bin` was loaded @ incorrect address. https://github.com/SymbiFlow/symbiflow-examples/commit/2bc55db818a7ae6b6bb1edaea32c04938c01db0b fixes this

**Comment by tcal-x** [comment]
Yep, fixed.  Thanks @kgugala !
